#ifndef ASTERIXPARSER_GLOBAL_H
#define ASTERIXPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASTERIXPARSER_LIBRARY)
#  define ASTERIXPARSER_EXPORT Q_DECL_EXPORT
#else
#  define ASTERIXPARSER_EXPORT Q_DECL_IMPORT
#endif

#endif // ASTERIXPARSER_GLOBAL_H
